services:
  postgres:
    image: postgres:16
    container_name: payments-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments_user
      POSTGRES_PASSWORD: payments_password
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: