spring:
  application:
    name: payment-processing-system

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      connection-timeout: 3000
      validation-timeout: 2000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  jackson:
    generator:
      write-bigdecimal-as-plain: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: db
        liveness:
          exclude: db